// Class: ReadCuts
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::Cuts
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/01       [335873]
Creator        : s0786887
Date           : Tue Aug 14 15:23:19 2012
Host           : Linux lxbuild147.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:51:11 CET 2010 i686 i686 i386 GNU/Linux
Dir            : /phys/linux/s0786887/Desktop/SummerProject/Edinburgh_H2bbAnalysis/WHanalysis/OutputTreeAnalysis/TMVA/Classification
Training events: 73852
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 2
fatjetPt[0]                   fatjetPt_0_                   fatjetPt[0]                   fatjetPt[0]                                                     'F'    [7.82528018951,179466.578125]
abs(Wphi-fatjetPhi[0])        abs_Wphi_M_fatjetPhi_0__      abs(Wphi-fatjetPhi[0])        DeltaPhiWH                                                      'F'    [0.000261068344116,6.22710800171]
NSpec 54
nhiggsJetSubjets              nhiggsJetSubjets              nhiggsJetSubjets              nhiggsJetSubjets                                                'F'    [0,3]
njets                         njets                         njets                         njets                         njets                             'F'    [0,19]
jetPt[0]                      jetPt_0_                      jetPt[0]                      jetPt[0]                                                        'F'    [20.0340690613,1214.11889648]
jetPt[1]                      jetPt_1_                      jetPt[1]                      jetPt[1]                                                        'F'    [0,820.003967285]
jetPt[2]                      jetPt_2_                      jetPt[2]                      jetPt[2]                                                        'F'    [0,385.307922363]
jetPt[3]                      jetPt_3_                      jetPt[3]                      jetPt[3]                                                        'F'    [0,295.785095215]
jetPt[4]                      jetPt_4_                      jetPt[4]                      jetPt[4]                                                        'F'    [0,278.474121094]
jetPt[5]                      jetPt_5_                      jetPt[5]                      jetPt[5]                                                        'F'    [0,200.728652954]
jetPt[6]                      jetPt_6_                      jetPt[6]                      jetPt[6]                                                        'F'    [0,167.485366821]
jetPt[7]                      jetPt_7_                      jetPt[7]                      jetPt[7]                                                        'F'    [0,91.595123291]
jetPt[8]                      jetPt_8_                      jetPt[8]                      jetPt[8]                                                        'F'    [0,80.0882339478]
jetPt[9]                      jetPt_9_                      jetPt[9]                      jetPt[9]                                                        'F'    [0,78.231842041]
jetPt[10]                     jetPt_10_                     jetPt[10]                     jetPt[10]                                                       'F'    [0,40.0147666931]
jetEta[0]                     jetEta_0_                     jetEta[0]                     jetEta[0]                                                       'F'    [-4.41487216949,4.34295320511]
jetEta[1]                     jetEta_1_                     jetEta[1]                     jetEta[1]                                                       'F'    [-4.48312044144,4.49045038223]
jetEta[2]                     jetEta_2_                     jetEta[2]                     jetEta[2]                                                       'F'    [-4.49213123322,4.49494886398]
jetEta[3]                     jetEta_3_                     jetEta[3]                     jetEta[3]                                                       'F'    [-4.49730491638,4.49716234207]
jetEta[4]                     jetEta_4_                     jetEta[4]                     jetEta[4]                                                       'F'    [-4.49886131287,4.49568367004]
jetEta[5]                     jetEta_5_                     jetEta[5]                     jetEta[5]                                                       'F'    [-4.49174785614,4.47183179855]
jetEta[6]                     jetEta_6_                     jetEta[6]                     jetEta[6]                                                       'F'    [-4.49406242371,4.49315977097]
jetEta[7]                     jetEta_7_                     jetEta[7]                     jetEta[7]                                                       'F'    [-4.47894859314,4.45641517639]
jetEta[8]                     jetEta_8_                     jetEta[8]                     jetEta[8]                                                       'F'    [-4.37361049652,4.46670436859]
jetEta[9]                     jetEta_9_                     jetEta[9]                     jetEta[9]                                                       'F'    [-4.45522403717,4.43440818787]
jetEta[10]                    jetEta_10_                    jetEta[10]                    jetEta[10]                                                      'F'    [-4.36382436752,4.45782709122]
jetPhi[0]                     jetPhi_0_                     jetPhi[0]                     jetPhi[0]                                                       'F'    [-3.14159035683,3.14149904251]
jetPhi[1]                     jetPhi_1_                     jetPhi[1]                     jetPhi[1]                                                       'F'    [-3.14139008522,3.14147758484]
jetPhi[2]                     jetPhi_2_                     jetPhi[2]                     jetPhi[2]                                                       'F'    [-3.14149141312,3.1415848732]
jetPhi[3]                     jetPhi_3_                     jetPhi[3]                     jetPhi[3]                                                       'F'    [-3.14157867432,3.14134335518]
jetPhi[4]                     jetPhi_4_                     jetPhi[4]                     jetPhi[4]                                                       'F'    [-3.14151597023,3.14110469818]
jetPhi[5]                     jetPhi_5_                     jetPhi[5]                     jetPhi[5]                                                       'F'    [-3.14157700539,3.14154863358]
jetPhi[6]                     jetPhi_6_                     jetPhi[6]                     jetPhi[6]                                                       'F'    [-3.13967037201,3.14150452614]
jetPhi[7]                     jetPhi_7_                     jetPhi[7]                     jetPhi[7]                                                       'F'    [-3.1396420002,3.13969063759]
jetPhi[8]                     jetPhi_8_                     jetPhi[8]                     jetPhi[8]                                                       'F'    [-3.13951349258,3.13629460335]
jetPhi[9]                     jetPhi_9_                     jetPhi[9]                     jetPhi[9]                                                       'F'    [-3.08359336853,3.13556027412]
jetPhi[10]                    jetPhi_10_                    jetPhi[10]                    jetPhi[10]                                                      'F'    [-3.08210802078,3.1404633522]
jetE[0]                       jetE_0_                       jetE[0]                       jetE[0]                                                         'F'    [21.3506832123,3370.32666016]
jetE[1]                       jetE_1_                       jetE[1]                       jetE[1]                                                         'F'    [0,3013.96557617]
jetE[2]                       jetE_2_                       jetE[2]                       jetE[2]                                                         'F'    [0,2724.12060547]
higgsJetSubjetEta[0]          higgsJetSubjetEta_0_          higgsJetSubjetEta[0]          higgsJetSubjetEta[0]                                            'F'    [-2.81778025627,3.64443564415]
higgsJetSubjetEta[1]          higgsJetSubjetEta_1_          higgsJetSubjetEta[1]          higgsJetSubjetEta[1]                                            'F'    [-3.75797796249,3.80041694641]
higgsJetSubjetEta[2]          higgsJetSubjetEta_2_          higgsJetSubjetEta[2]          higgsJetSubjetEta[2]                                            'F'    [-3.37136673927,3.17541718483]
higgsJetSubjetPhi[0]          higgsJetSubjetPhi_0_          higgsJetSubjetPhi[0]          higgsJetSubjetPhi[0]                                            'F'    [-3.14158964157,3.14154958725]
higgsJetSubjetPhi[1]          higgsJetSubjetPhi_1_          higgsJetSubjetPhi[1]          higgsJetSubjetPhi[1]                                            'F'    [-3.14146876335,3.14152884483]
higgsJetSubjetPhi[2]          higgsJetSubjetPhi_2_          higgsJetSubjetPhi[2]          higgsJetSubjetPhi[2]                                            'F'    [-3.14144897461,3.14088869095]
higgsJetSubjetPt[0]           higgsJetSubjetPt_0_           higgsJetSubjetPt[0]           higgsJetSubjetPt[0]                                             'F'    [0,778881.75]
higgsJetSubjetPt[1]           higgsJetSubjetPt_1_           higgsJetSubjetPt[1]           higgsJetSubjetPt[1]                                             'F'    [0,400363.375]
higgsJetSubjetPt[2]           higgsJetSubjetPt_2_           higgsJetSubjetPt[2]           higgsJetSubjetPt[2]                                             'F'    [0,303241.53125]
higgsJetSubjetE[0]            higgsJetSubjetE_0_            higgsJetSubjetE[0]            higgsJetSubjetE[0]                                              'F'    [0,1898733]
higgsJetSubjetE[1]            higgsJetSubjetE_1_            higgsJetSubjetE[1]            higgsJetSubjetE[1]                                              'F'    [0,1314147.75]
higgsJetSubjetE[2]            higgsJetSubjetE_2_            higgsJetSubjetE[2]            higgsJetSubjetE[2]                                              'F'    [0,697943.6875]
Wphi                          Wphi                          Wphi                          Wphi                                                            'F'    [-3.14158797264,3.1415643692]
fatjetPhi[0]                  fatjetPhi_0_                  fatjetPhi[0]                  fatjetPhi[0]                                                    'F'    [-3.14148545265,3.14152812958]
fatjetEta[0]                  fatjetEta_0_                  fatjetEta[0]                  fatjetEta[0]                                                    'F'    [-99999997952,3.48850345612]
fatjetE[0]                    fatjetE_0_                    fatjetE[0]                    fatjetE[0]                                                      'F'    [-999,479103.5]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCuts : public IClassifierReader {

 public:

   // constructor
   ReadCuts( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCuts" ),
        fNvars( 2 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "fatjetPt[0]", "abs(Wphi-fatjetPhi[0])" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 7.82528018951416;
      fVmax[0] = 179466.578125;
      fVmin[1] = 0.000261068344116211;
      fVmax[1] = 6.22710800170898;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCuts() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[2];
   double fVmax[2];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[2];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCuts"
};
   inline double ReadCuts::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
